### ISSUE TITLE
Incorrect typings

### ISSUE THREAD

**Issue by Jazcash** [robertcorponoi/pixi-game-camera#9]
Some of the typings make some properties required instead of optional, which are said to be not required in the readme:

![image](https://user-images.githubusercontent.com/1434248/108192644-6dc36400-710c-11eb-9b0c-1e8794951ee1.png)

![image](https://user-images.githubusercontent.com/1434248/108192664-7451db80-710c-11eb-91ae-3e7bf8032126.png)

**Comment by robertcorponoi** [comment]
Sorry about that, I'll have it fixed within the next day.

**Comment by robertcorponoi** [comment]
Sorry for the delay, been crazy here in Austin. These the optional arguments for what you provided and a couple other effects should be correct now. Thank you for bringing this issue up.
